on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 5

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - uses: actions/setup-python@v6

      - uses: astral-sh/setup-uv@v7

      - run: |
          uv tool install gersemi

      - uses: actions/cache@v5
        id: deps
        with:
          path: |
            "${{ github.workspace }}/build/_deps"
          key: "deps-${{ hashFiles('libs/CMakeLists.txt') }}"

      - run: |
          cmake --preset release && cmake --build --preset release

  notify:
    needs: release
    uses: ./.github/workflows/notify.yaml
    secrets: inherit
